Courses.create!([
  {name: "Diploma in Computer Science"},
  {name: "Diploma in Computer Engineering"},
  {name: "Diploma in Computer Technology"},
  {name: "Diploma in Information Technology"},
  {name: "Diploma in Information Systems"},
])
GdCenters.create!([
  {place: "Bangalore"},
  {place: "Chennai"},
  {place: "Pune"},
  {place: "Gurgaon"},
  {place: "Vijayawada"},
  {place: "Hyderabad"},
  {place: "Delhi"},
])
User.create!([
  {name: "sandeep", date_of_birth: "1996-07-12", gender: "Male", email: "sinha.sandeep01@gmail.com", address: nil, city: "che", mobile_number: "8939200476", course: "Diploma in Computer Engineering", year_of_pass: "2013", preferred_aptitude_center: "Chennai", preferred_gd_center: "Chennai"},
  {name: "hello", date_of_birth: "1996-07-12", gender: "Male", email: "abc@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "123@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "ijk@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "lmk@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "poi@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "sample@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "wour@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "dupm@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "step@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "12345@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "890@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "456@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "7689@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "0898@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "56757@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "34535@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "96876@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "7687576@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "08908@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "1414@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "90@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "243254@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "kjhk@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "ryti@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "cbvcn@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "6876@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "ljlkk@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "werw@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "yuti@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "pipp@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "qreqr@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "poipo@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "chghg@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "r7r7@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "vnbvn@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"},
  {name: "san", date_of_birth: "1996-07-12", gender: "Male", email: "cxzcv@gmail.com", address: nil, city: "sjdvhsd", mobile_number: "76986", course: "Diploma in Computer Science", year_of_pass: "2012", preferred_aptitude_center: "Bangalore", preferred_gd_center: "Bangalore"}
])
